// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EliMZ_Book","status":true,"description":"v4.1.8 - Essential plugin for all Eli plugins.","parameters":{"engine":"{\"mvAnimation\":\"{\\\"enable\\\":\\\"false\\\",\\\"directory\\\":\\\"\\\",\\\"smooth\\\":\\\"false\\\",\\\"rate\\\":\\\"4\\\"}\",\"pixelPerfect\":\"false\",\"disableEffekseer\":\"false\",\"styleOverflow\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"gameFocus\":\"false\",\"quickRestart\":\"true\"}"}},
{"name":"EliMZ_SelfVariables","status":true,"description":"v3.1.1 - Self Variables fully integrated with events!","parameters":{"eventIdVar":"0","mapIdVar":"0"}},
{"name":"EliMZ_SelfSwitches","status":true,"description":"v3.1.3 - Enhance the self switch commands and functionality.","parameters":{}},
{"name":"GRB_SelfVarsAndSwitches","status":true,"description":"Self variables and more self-switches","parameters":{"prefixes":"[\"(Лок.)\",\"(лок.)\",\"(Лак.)\",\"(лак.)\",\"(Self)\",\"(self)\"]"}},
{"name":"GRB_SelfVarsAndSwitches","status":true,"description":"Self variables and more self-switches","parameters":{"prefixes":"[\"(Лок.)\",\"(лок.)\",\"(Лак.)\",\"(лак.)\",\"(Self)\",\"(self)\"]"}}
];
